CREATE TABLE `stock_count_temp` (
  `id` int(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `storeid` varchar(128) DEFAULT NULL,
  `departmentid` varchar(128) DEFAULT NULL,
  `code` varchar(250) DEFAULT NULL COMMENT 'sku',
  `initial` int(20) NOT NULL DEFAULT 0 COMMENT 'Expected',
  `counted` int(20) NOT NULL DEFAULT 0,
  `delta` varchar(250) DEFAULT NULL,
  `unexpected` int(20) NOT NULL DEFAULT 0 COMMENT 'extra(over)',
  `missing` int(20) NOT NULL DEFAULT 0 COMMENT 'under',
  `expected` int(20) NOT NULL DEFAULT 0 COMMENT 'Match',
  `accuracy` varchar(100) DEFAULT NULL,
  `expected_sf` int(250) NOT NULL DEFAULT 0,
  `expected_sr` int(20) NOT NULL DEFAULT 0,
  `counted_sf` int(20) NOT NULL DEFAULT 0,
  `counted_sr` int(20) NOT NULL DEFAULT 0,
  `scanned` int(20) DEFAULT NULL,
  `stockcountdate` date DEFAULT NULL,
  `brand_name` varchar(256) DEFAULT NULL,
  `color` varchar(128) DEFAULT NULL,
  `size` varchar(128) DEFAULT NULL,
  `style` varchar(256) DEFAULT NULL,
  `price` varchar(250) DEFAULT NULL,
  `season` varchar(250) DEFAULT NULL,
  `extra_item` int(20) NOT NULL DEFAULT 0,
  `is_deleted` int(20) NOT NULL DEFAULT 0,
  `suppliername` varchar(250) DEFAULT NULL,
  `totalprice` varchar(250) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4